# Generated by Django 4.2 on 2023-04-04 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Language_ID')),
                ('srclang', models.CharField(max_length=8, verbose_name='Language_Code')),
                ('label', models.CharField(max_length=100, verbose_name='Language_Label')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Series_ID')),
                ('original_id', models.CharField(max_length=100, verbose_name='Original_ID')),
                ('title_en', models.CharField(max_length=100, verbose_name='Series Title(English)')),
                ('title_jp', models.CharField(max_length=100, verbose_name='Series Title(Japanese)')),
                ('source', models.CharField(default='crunchyroll', max_length=100, verbose_name='Source')),
                ('poster', models.URLField(verbose_name='Series Poster')),
                ('date', models.DateField(verbose_name='Date')),
                ('remark', models.TextField(verbose_name='Remark')),
                ('available', models.BooleanField(default=False, verbose_name='Available')),
                ('subtitles', models.ManyToManyField(to='core.subtitle')),
            ],
            options={
                'ordering': ['-date', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeCrunchyroll',
            fields=[
                ('number', models.CharField(max_length=100, verbose_name='Episode_NUmber')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, verbose_name='Webpage')),
                ('name', models.CharField(max_length=100, verbose_name='Episode Title')),
                ('poster', models.URLField(verbose_name='Poster')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.DurationField(null=True, verbose_name='Duration')),
                ('offset', models.SmallIntegerField(default=0, verbose_name='Offset')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.series', verbose_name='Series')),
            ],
            options={
                'ordering': ['series', 'number'],
                'unique_together': {('series', 'number')},
            },
        ),
    ]
