# Generated by Django 4.2 on 2023-04-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='subtitles',
        ),
        migrations.DeleteModel(
            name='EpisodeCrunchyroll',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='Subtitle',
        ),
    ]
