# Generated by Django 4.2 on 2023-04-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_action_user_anime_name_anime_user_family_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='user',
        ),
        migrations.RemoveField(
            model_name='family',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kids',
            name='user',
        ),
        migrations.RemoveField(
            model_name='popular',
            name='user',
        ),
    ]
